package usecase

import (
	"fmt"
	"os"

	"github.com/google/uuid"
)

func createFolder() (string, error) {
	folderName := uuid.New().String()
	folderPath := "./internal/module/latex_compiler/latex_source/" + folderName
	err := os.Mkdir(folderPath, os.ModeAppend)
	if err != nil {
		return "", err
	}
	texContent := `\documentclass{article}
\usepackage[utf8]{inputenc}
\title{Hello, World!}
\author{Your Name}
\date{\today}
\begin{document}
\maketitle
\section{Introduction}
This is a simple LaTeX document generated by Golang.
\end{document}`

	// Tên file .tex
	fileName := folderPath + "/output.tex"

	// Tạo và mở file .tex
	file, err := os.Create(fileName)
	if err != nil {
		fmt.Println("Error creating file:", err)
		return "", err
	}
	defer file.Close()

	// Ghi nội dung vào file .tex
	_, err = file.WriteString(texContent)
	if err != nil {
		fmt.Println("Error writing to file:", err)
		return "", err
	}

	fmt.Println("File created successfully:", fileName)
	return folderPath, nil
}

func deleteFolder(folderPath string) error {
	err := os.RemoveAll(folderPath)
	fmt.Print(folderPath)
	if err != nil {
		fmt.Print(err.Error())
		return err
	}

	return nil
}
